version: '3.9'
services:
  api:
    build: .
    image: where-to-eat-api
    container_name: api
    ports:
      - "8080:8080"
    environment:
      spring.profiles.active: production
    depends_on:
      - db
  db:
    container_name: db
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - 2022:1433
    volumes:
      - data:/var/lib/mssqlql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Aaservidor1234*
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
      - MSSQL_TCP_PORT=1433
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
   data: {}