version: '3.9'
services:
  api:
    build: .
    image: where-to-eat-api
    container_name: api-pro
    ports:
      - "2022:8080"
    environment:
      spring.profiles.active: pro
    depends_on:
      - db

  db:
    container_name: db-pro
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - 1434:1433
    volumes:
      - data:/var/lib/mssqlql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Aaservidor1234*
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
      - MSSQL_TCP_PORT=1433

volumes:
   data-pro: {}